const sb=window.supabase.createClient(SINO_SUPABASE.url,SINO_SUPABASE.key);
var lang=localStorage.getItem("sino_lang")||"ar",cart=JSON.parse(localStorage.getItem("sino_cart")||"[]"),category="all",sortMode="popular",PRODUCTS=[];
var ICONS={"youtube-premium":"https://cdn.simpleicons.org/youtube/FF0000","spotify-premium":"https://cdn.simpleicons.org/spotify/1ED760","netflix":"https://cdn.simpleicons.org/netflix/E50914","chatgpt-plus":"https://cdn.simpleicons.org/openai/FFFFFF","chatgpt-go":"https://cdn.simpleicons.org/openai/FFFFFF","discord-nitro":"https://cdn.simpleicons.org/discord/5865F2","shahid-vip":"https://cdn.simpleicons.org/shahid/FFFFFF","xbox-game-pass":"https://cdn.simpleicons.org/xbox/107C10","playstation-plus":"https://cdn.simpleicons.org/playstation/FFFFFF","canva-pro":"https://cdn.simpleicons.org/canva/00C4CC","apple-music":"https://cdn.simpleicons.org/applemusic/FFFFFF","snapchat-plus":"https://cdn.simpleicons.org/snapchat/FFFC00","x-premium":"https://cdn.simpleicons.org/x/FFFFFF","anghami-plus":"https://cdn.simpleicons.org/anghami/FFFFFF","pubg-uc":"https://cdn.simpleicons.org/pubg/FFB000"};
var $=function(s){return document.querySelector(s)},$$=function(s){return Array.from(document.querySelectorAll(s))};
function money(n){return Number(n).toLocaleString(lang==="ar"?"ar-EG":"en-US")+" "+(lang==="ar"?"ج.م":"EGP")}
function pname(p){return lang==="ar"?p.name_ar:p.name_en}
function dur(n){if(!n)return lang==="ar"?"فوري":"Instant";if(n===1)return lang==="ar"?"شهر":"1 month";return n+" "+(lang==="ar"?"شهور":"months")}
function desc(p){var d={streaming:["أفلام ومسلسلات وتجربة ترفيهية مميزة.","Movies, series and premium entertainment."],music:["موسيقى وبودكاست بدون إعلانات.","Music and podcasts without ads."],ai:["أدوات ذكاء اصطناعي وإنتاجية أعلى.","AI and productivity tools."],gaming:["ألعاب وترفيه رقمي.","Gaming and digital entertainment."],social:["مزايا اجتماعية رقمية إضافية.","Extra social features."],creative:["أدوات تصميم وإبداع.","Creative and design tools."]};return (d[p.category]||["خدمة رقمية مميزة.","Premium digital service."])[lang==="ar"?0:1]}
function logo(p){return ICONS[p.slug]?'<img src="'+ICONS[p.slug]+'" alt="'+p.name_en+'" loading="lazy" onerror="this.style.display=\'none\'">':'<span>'+p.name_en.slice(0,2).toUpperCase()+'</span>'}
function groups(){var m={};PRODUCTS.filter(function(p){return p.slug!=="pubg-uc"}).filter(function(p){return category==="all"||p.category===category}).forEach(function(p){m[p.slug]=m[p.slug]||[];m[p.slug].push(p)});return Object.values(m)}
function renderServices(){
 var gs=groups();
 if(sortMode==="price")gs.sort(function(a,b){return a[0].price-b[0].price});
 $("#grid").innerHTML=gs.map(function(g){var p=g[0];return '<article class="product-card reveal"><div class="pt"><span class="tag">'+p.category+'</span><button class="heart">♡</button></div><div class="plogo">'+logo(p)+'</div><h3>'+pname(p)+'</h3><p>'+desc(p)+'</p><span class="plan-label">'+(lang==="ar"?"اختار المدة":"Choose duration")+'</span><select class="plan" data-slug="'+p.slug+'">'+g.sort(function(a,b){return a.months-b.months}).map(function(x){return '<option value="'+x.id+'">'+dur(x.months)+" — "+money(x.price)+'</option>'}).join("")+'</select><div class="price"><small>'+ (lang==="ar"?"السعر":"Price") +'</small><strong>'+money(p.price)+'</strong></div><button class="btn primary full add-service" data-slug="'+p.slug+'">'+(lang==="ar"?"أضف للسلة":"Add to cart")+'</button></article>'}).join("");
 $$(".plan").forEach(function(s){s.onchange=function(){var p=PRODUCTS.find(function(x){return String(x.id)===s.value});s.closest(".product-card").querySelector(".price strong").textContent=money(p.price)}});
 $$(".add-service").forEach(function(b){b.onclick=function(){var s=b.dataset.slug,sel=$('.plan[data-slug="'+s+'"]'),p=PRODUCTS.find(function(x){return String(x.id)===sel.value});if(!p)return;cart.push({product_id:p.id,name_ar:p.name_ar,name_en:p.name_en,name:pname(p),meta:dur(p.months),price:Number(p.price)});save();updateCart();openCart()}})
 observe()
}
function renderPubg(){
 var ps=PRODUCTS.filter(function(p){return p.slug==="pubg-uc"}).sort(function(a,b){return Number(a.metadata.uc||a.base_price)-Number(b.metadata.uc||b.base_price)});
 $("#pubgGrid").innerHTML=ps.map(function(p){var uc=p.metadata&&p.metadata.uc?p.metadata.uc:p.name_en.replace(/\D/g,"");return '<article class="product-card reveal"><div class="pt"><span class="tag">PUBG UC</span><span class="uc-price">UC</span></div><div class="plogo">'+logo(p)+'</div><h3>'+pname(p)+'</h3><p>'+ (lang==="ar"?"شحن مباشر بالـPlayer ID":"Top-up by Player ID") +'</p><div class="price"><small>'+ (lang==="ar"?"السعر الأساسي":"Base price") +'</small><strong>'+money(p.price)+'</strong></div><input class="player" data-id="'+p.id+'" placeholder="Player ID" inputmode="numeric"><button class="btn full pubg-add" data-id="'+p.id+'">'+(lang==="ar"?"أضف للسلة":"Add to cart")+'</button></article>'}).join("");
 $$(".pubg-add").forEach(function(b){b.onclick=function(){var p=ps.find(function(x){return String(x.id)===b.dataset.id}),input=$('.player[data-id="'+p.id+'"]'),pid=input.value.trim();if(!pid){toast(lang==="ar"?"اكتب Player ID الأول.":"Enter Player ID first.");return}cart.push({product_id:p.id,name_ar:p.name_ar,name_en:p.name_en,name:pname(p),meta:"ID: "+pid,price:Number(p.price),player_id:pid});save();updateCart();openCart()}})
 observe()
}
function renderFilters(){var labels={all:["الكل","All"],streaming:["فيديو","Video"],music:["موسيقى","Music"],ai:["ذكاء اصطناعي","AI"],gaming:["ألعاب","Gaming"],social:["سوشيال","Social"],creative:["إبداع","Creative"]};var html=Object.keys(labels).map(function(k){return '<button class="sort '+(category===k?"active":"")+'" data-category="'+k+'">'+labels[k][lang==="ar"?0:1]+"</button>"}).join("");if($("#grid")){$("#grid").insertAdjacentHTML("beforebegin","<div class='toolbar filters'>"+html+"</div>");var tb=$(".toolbar.filters");if(tb){$$(".toolbar.filters .sort").forEach(function(b){b.onclick=function(){category=b.dataset.category;tb.remove();renderFilters();renderServices()}})}}}
function renderBundles(){var data=[["Entertainment Pack",749,["youtube-premium","netflix","spotify-premium"]],["Productivity Pro",699,["chatgpt-plus","chatgpt-go","canva-pro"]],["Gaming & Entertainment",599,["playstation-plus","xbox-game-pass","netflix"]]];var el=$("#b1")?null:$("#bundles");if(!el)return;var target=$("#bundlesGrid");if(target){target.innerHTML=data.map(function(b){return '<article class="bundle-card"><div class="bundle-icons">'+b[2].map(function(sl){var p=PRODUCTS.find(function(x){return x.slug===sl});return p?'<span>'+logo(p)+'</span>':""}).join("")+'</div><div><small>★ '+(lang==="ar"?"قيمة مميزة":"Best value")+'</small><h3>'+b[0]+'</h3><p>'+ (lang==="ar"?"مجموعة خدمات مرتبة في باقة واحدة.":"A curated mix of useful services.") +'</p><strong>'+money(b[1])+'</strong><button class="btn primary bundle-btn" data-name="'+b[0]+'" data-price="'+b[1]+'">'+(lang==="ar"?"اطلب الباقة":"Order bundle")+'</button></div></article>'}).join("");$$(".bundle-btn").forEach(function(b){b.onclick=function(){cart.push({name:b.dataset.name,meta:"Bundle",price:Number(b.dataset.price)});save();updateCart();openCart()}})}}
function updateCart(){if(!$("#cartItems"))return;$("#cartCount").textContent=cart.length;$("#cartItems").innerHTML=cart.length?cart.map(function(x,i){return '<div class="cart-row"><div><b>'+x.name+'</b><small>'+x.meta+'</small></div><strong>'+money(x.price)+'</strong><button class="remove" data-i="'+i+'">×</button></div>'}).join(""):'<div class="empty">🛍<p>'+ (lang==="ar"?"السلة فاضية حاليًا.":"Your cart is empty.")+'</p></div>';$$(".remove").forEach(function(b){b.onclick=function(){cart.splice(Number(b.dataset.i),1);save();updateCart()}});$("#cartTotal").textContent=money(cart.reduce(function(a,x){return a+x.price},0))}
function save(){localStorage.setItem("sino_cart",JSON.stringify(cart))}
function openCart(){$("#drawer").classList.add("open");$("#back").classList.add("open")}
function closeCart(){$("#drawer").classList.remove("open");$("#back").classList.remove("open")}
async function checkout(){if(!cart.length)return;var u=await sb.auth.getUser();if(!u.data.user){location.href="login.html?next=checkout";return}var total=cart.reduce(function(a,x){return a+x.price},0);var ins=await sb.from("orders").insert({user_id:u.data.user.id,total:total,payment_method:"manual"}).select().single();if(ins.error){toast(lang==="ar"?"تعذر إنشاء الطلب":"Could not create order");return}var rows=cart.map(function(x){return {order_id:ins.data.id,product_id:x.product_id||null,product_name_ar:x.name_ar||x.name,product_name_en:x.name_en||x.name,months:0,quantity:1,unit_price:x.price,player_id:x.player_id||null}});await sb.from("order_items").insert(rows);var msg="SINO-STORE\nOrder #"+ins.data.id+"\n"+cart.map(function(x){return x.name+" | "+x.meta+" | "+money(x.price)}).join("\n")+"\nTotal: "+money(total)+"\nInstaPay: 01096977761\nVodafone Cash: 01002633244";cart=[];save();updateCart();window.open("https://wa.me/201002633244?text="+encodeURIComponent(msg),"_blank");closeCart();toast(lang==="ar"?"تم إنشاء الطلب وإرساله للمراجعة.":"Order created and sent for review.")}
function applyLang(){document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr";$$("[data-ar]").forEach(function(e){e.innerHTML=e.dataset[lang]});$("#langBtn").textContent=lang==="ar"?"EN":"AR";$("#search").placeholder=lang==="ar"?"ابحث عن اشتراك أو خدمة...":"Search subscriptions or services...";localStorage.setItem("sino_lang",lang);var oldFilter=$(".filters.toolbar");if(oldFilter)oldFilter.remove();renderFilters();renderServices();renderPubg();updateCart()}
function observe(){if(!window.IntersectionObserver)return;var io=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting)e.target.classList.add("visible")})},{threshold:.05});$$(".reveal").forEach(function(e){io.observe(e)})}
function toast(t){var x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(function(){x.classList.remove("show")},2000)}
async function init(){var r=await sb.from("products").select("*").eq("active",true).order("sort_order");if(r.error){toast(lang==="ar"?"تعذر تحميل البيانات":"Could not load data");return}PRODUCTS=r.data||[];renderFilters();renderServices();renderPubg();renderBundles();updateCart();applyLang()}
$("#langBtn").onclick=function(){lang=lang==="ar"?"en":"ar";applyLang()};$("#searchBtn").onclick=function(){$("#searchBar").classList.toggle("open")};$("#cartBtn").onclick=openCart;$("#closeCart").onclick=closeCart;$("#back").onclick=closeCart;$("#checkoutBtn").onclick=checkout;$("#search").oninput=renderServices;
init();